name: UPM
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found
        git checkout upm
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git merge -s theirs origin/main
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
        fi
        if [[ -f ".gitignore" ]]; then
          rm .gitignore
        fi
        if [[ -d ".github" ]]; then
          rm -f -r .github
        fi
        if [[ `git status --porcelain` ]]; then
          git commit -am "Release~"
          git push -f -u origin upm
        fi
